version: '3.1'

volumes:
  vol-database:

services:
  database:
    image: mysql:latest
    container_name: aipixel_database_container
    hostname: aipixel_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: aipixel.user
      MYSQL_PASSWORD: aipixel.pass
      MYSQL_DATABASE: aipixel-db
    volumes:
      - vol-database:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  app:
    profiles: [ "app" ]
    image: maven:3-eclipse-temurin-21-alpine
    container_name: aipixel_app_container
    hostname: aipixel_app
    depends_on:
      - database
    environment:
      DATABASE_URL: jdbc:mysql://database:3306/aipixel-db?allowPublicKeyRetrieval=true
      DATABASE_USER: aipixel.user
      DATABASE_PASSWORD: aipixel.pass
      RESOURCES_PATHS: "'file:./public/'"
      IMAGES_DIRECTORY: ./public/resources/images
      IMAGES_URL: /api/v1/resources/images
      IMAGES_DEFAULT_LIMIT: 25
      CORS_ALLOWED_ORIGINS: http://localhost:63343
      CORS_ALLOWED_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
      CORS_ALLOWED_HEADERS: "*"
      CORS_ALLOW_CREDENTIALS: true
    working_dir: /app
    command: >
      sh -c "echo 'Building the application...'
      && mvn -U clean install -DskipTests=true 
      && echo 'Launching the application...'
      && java -jar target/ai-pixel-v1.0.0-SNAPSHOT.jar"
    volumes:
      - ./:/app
    ports:
      - 8080:8080