logging:
  level:
    org:
      springframework: DEBUG

app:
  images:
    directory: ./images
    default-limit: 5

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

spring:
  mvc:
    servlet:
      path: /api

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/aipixel-db
    username: aipixel.user
    password: aipixel.pass