server:
  port: 8080

app:
  name: &app-name ai-pixel

  images:
    directory: ${IMAGES_DIRECTORY}
    url: ${IMAGES_URL}
    default-limit: ${IMAGES_DEFAULT_LIMIT}

  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS}
      allowed-headers: ${CORS_ALLOWED_HEADERS}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS}

spring:
  application:
    name: *app-name

  mvc:
    servlet:
      path: /api/v1

  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver