logging:
  level:
    org:
      springframework: DEBUG

images:
  url:
    base: /api/resources/images

spring:
  mvc:
    servlet:
      path: /api

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/aipixel-db
    username: aipixel.user
    password: aipixel.pass