logging:
  level:
    org:
      springframework: DEBUG

jpa:
  show-sql: true

spring:
  mvc:
    servlet:
      path: /api

  datasource:
    url: jdbc:mysql://localhost:3306/aipixel-db
    username: aipixel.user
    password: aipixel.pass