logging:
  level:
    org:
      springframework: DEBUG

app:
  images:
    directory: ./public/resources/images
    url:  /api/resources/images

  web:
    cors:
      allowed-origins: "http://localhost:63343"
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

    resources:
      paths: "'file:./public/'"

spring:
  mvc:
    servlet:
      path: /api

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/aipixel-db
    username: aipixel.user
    password: aipixel.pass