server:
  port: 8080

manager:
  file:
    directory: ./public/resources/images

spring:
  application:
    name: ai-pixel

  web:
    resources:
      static-locations: ./public

  mvc:
    servlet:
      path: /api/v1

  multipart:
    enabled: true
    max-file-size: 100MB
    max-request-size: 100MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver