USE aipixel-db;

CREATE TABLE categories(
	id BIGINT NOT NULL,
    name VARCHAR( 25 ) NOT NULL UNIQUE,
	description TEXT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	-- KEYS
	PRIMARY KEY( id )
) ENGINE = InnoDB CHARSET = utf8;



CREATE TABLE tags(
    id BIGINT NOT NULL,
    name VARCHAR( 20 ) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- KEYS
    PRIMARY KEY( id )
) ENGINE = InnoDB CHARSET = utf8;



CREATE TABLE images(
    id CHAR( 36 ) NOT NULL,
    favorite BOOLEAN NOT NULL DEFAULT false,
    date DATE NULL,
    name VARCHAR( 50 ) NOT NULL,
    file_name VARCHAR( 250 ) NOT NULL UNIQUE,
    description TEXT NULL,
    valoration TINYINT NULL CHECK (valoration BETWEEN 1 AND 5),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- KEYS
    PRIMARY KEY( id )
) ENGINE = InnoDB CHARSET = utf8;



CREATE TABLE images_categories(
    image_id CHAR( 36 ) NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- KEYS
    PRIMARY KEY( image_id, category_id ),
    FOREIGN KEY( image_id ) REFERENCES images( id )
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY( category_id ) REFERENCES categories( id )
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARSET = utf8;



CREATE TABLE images_tags(
    image_id CHAR( 36 ) NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- KEYS
    PRIMARY KEY( image_id, tag_id ),
    FOREIGN KEY( image_id ) REFERENCES images( id )
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY( tag_id ) REFERENCES tags( id )
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARSET = utf8;